@baseUrl = http://localhost:8000/api/v1
@token = 1|EhbH5CkTyy9xecs40fJc8fBgJlDjtIVfx71YPhNU71df2496

# Manager Role
# "email" => "rizkyjcd@jcdigital.co.id"
# "password" => atasizinAllah#2511

# Employee Role
# "email" => "employee@gmail.com"
# "password" => password

####################################
# AUTH
####################################

### Login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
  "email" : "rizkyjcd@jcdigital.co.id",
  "password" : "atasizinAllah#2511"
}

####################################
# PROFILE
####################################

### Get My Profile
GET {{baseUrl}}/me
Accept: application/json
Authorization: Bearer {{token}}

####################################
# TEAM
####################################

### Get All Teams
GET {{baseUrl}}/teams?search=Elang&leader_id=
Accept: application/json
Authorization: Bearer {{token}}

### Get Teams Paginated
GET {{baseUrl}}/teams/all/paginated?row_per_page=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Team By ID
GET {{baseUrl}}/teams/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Team
POST {{baseUrl}}/teams
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Team Elang",
  "department": "marketing",
  "responsibilities": [
    "Menagih hutang ke customer",
    "Mencatat keuangan",
    "Mematikan PDAM"
  ]
}

### Update Team
PUT {{baseUrl}}/teams/3
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Team Elang Update"
}

### Delete Team
DELETE {{baseUrl}}/teams/2
Accept: application/json
Authorization: Bearer {{token}}

####################################
# EMPLOYEE
####################################

### Get Employees
GET {{baseUrl}}/employees?status=active&type=full_time&work_location=
Accept: application/json
Authorization: Bearer {{token}}

### Get Employees Paginated
GET {{baseUrl}}/employees/all/paginated?row_per_page=10
Accept: application/json
Authorization: Bearer {{token}}

### Create Employee
POST {{baseUrl}}/employees
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Muhamad Rafli Al Farizqi",
  "email": "rafli@employee.com",
  "password": "password",
  "identity_number": "2311102311",
  "phone": "085325483259",
  "date_of_birth": "2006-04-20",
  "gender": "male",
  "address": "Jalan Soekarno Hatta No 12",
  "city": "Jakarta",
  "postal_code": "52276",
  "job_title": "Backend Developer",
  "years_experience": 3,
  "job_status": "active",
  "employment_type": "full_time",
  "work_location": "remote",
  "start_date": "2025-09-18",
  "monthly_salary": 5000000,
  "skill_level": "advanced",
  "bank_name": "bri",
  "account_number": "88992131231",
  "account_holder_name": "Muhamad Rafli Al Farizqi",
  "account_type": "savings",
  "emergency_contacts": [
    "Grashela"
  ]
}

### Update Employee
PUT {{baseUrl}}/employees/2
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Joni",
  "email": "joni@employee.com",
  "job_title": "Frontend Developer",
  "status": "resigned",
  "employment_type": "contract",
  "monthly_salary": 300000
}

### Delete Employee
DELETE {{baseUrl}}/employees/2
Accept: application/json
Authorization: Bearer {{token}}

####################################
# PROJECT
####################################

### Get Projects
GET {{baseUrl}}/projects?search=design&status=active
Accept: application/json
Authorization: Bearer {{token}}

### Create Project
POST {{baseUrl}}/projects
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "E-commerce Platform Redesign",
  "type": "design",
  "priority": "high",
  "status": "draft",
  "start_date": "2025-09-20",
  "budget": 60000000
}

### Update Project
PUT {{baseUrl}}/projects/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "budget": 5000000,
  "teams": [1],
  "project_leader_id": 2
}

### Delete Project
DELETE {{baseUrl}}/projects/2
Accept: application/json
Authorization: Bearer {{token}}

####################################
# TASK
####################################

### Get Project Tasks
GET {{baseUrl}}/project-tasks?project_id=1
Accept: application/json
Authorization: Bearer {{token}}

### Create Task
POST {{baseUrl}}/project-tasks
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project_id": 1,
  "name": "Design Landing Page",
  "priority": "high",
  "status": "todo"
}

### Update Task
PUT {{baseUrl}}/project-tasks/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "done"
}

### Delete Task
DELETE {{baseUrl}}/project-tasks/2
Accept: application/json
Authorization: Bearer {{token}}

####################################
# ATTENDANCE
####################################

### Check In
POST {{baseUrl}}/attendances/check-in
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "check_in_lat": -7.451584,
  "check_in_long": 109.259628
}

### Check Out
POST {{baseUrl}}/attendances/check-out
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "check_out_lat": -7.451584,
  "check_out_long": 109.259628
}

####################################
# LEAVE REQUEST
####################################

### Create Leave Request
POST {{baseUrl}}/leave-requests
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "leave_type": "sick_leave",
  "start_date": "2025-09-20",
  "end_date": "2025-09-22",
  "reason": "lorem"
}

### Approve Leave
POST {{baseUrl}}/leave-requests/approve/2
Accept: application/json
Authorization: Bearer {{token}}

### Reject Leave
POST {{baseUrl}}/leave-requests/reject/1
Accept: application/json
Authorization: Bearer {{token}}

####################################
# PAYROLL
####################################

### Generate Payroll
POST {{baseUrl}}/payrolls/generate
Accept: application/json
Authorization: Bearer {{token}}

### Mark Payroll As Paid
POST {{baseUrl}}/payrolls/1/mark-as-paid
Accept: application/json
Authorization: Bearer {{token}}

####################################
# CREDENTIAL ACCOUNT
####################################

### Get All Credential Accounts
GET {{baseUrl}}/credential-accounts?search=GitHub&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Credential Accounts Paginated
GET {{baseUrl}}/credential-accounts/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Credential Account By ID
GET {{baseUrl}}/credential-accounts/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Credential Account
POST {{baseUrl}}/credential-accounts
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "label_password": "GitHub Account",
  "username_email": "developer@company.com",
  "password": "SecurePassword123!",
  "website": "https://github.com",
  "notes": "Main development account for version control"
}

### Update Credential Account
PUT {{baseUrl}}/credential-accounts/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "label_password": "GitHub Account Updated",
  "username_email": "dev@company.com",
  "password": "NewSecurePassword456!",
  "website": "https://github.com",
  "notes": "Updated development account"
}

### Delete Credential Account
DELETE {{baseUrl}}/credential-accounts/1
Accept: application/json
Authorization: Bearer {{token}}

####################################
# FILES COMPANY
####################################

### Get All Company Files
GET {{baseUrl}}/files-companies?search=handbook&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Company Files Paginated
GET {{baseUrl}}/files-companies/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Company File By ID
GET {{baseUrl}}/files-companies/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Company File
POST {{baseUrl}}/files-companies
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path": "company-files/policies/employee-handbook.pdf",
  "name": "Employee Handbook 2024",
  "description": "Complete employee handbook with company policies, code of conduct, and procedures"
}

### Update Company File
PUT {{baseUrl}}/files-companies/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path": "company-files/policies/employee-handbook-2024.pdf",
  "name": "Employee Handbook 2024 Updated",
  "description": "Updated employee handbook with latest policies"
}

### Delete Company File
DELETE {{baseUrl}}/files-companies/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# COMPANY FINANCE
####################################

### Get All SDM Resource
GET {{baseUrl}}/company-finances?search=GitHub&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Company Finances Paginated
GET {{baseUrl}}/company-finances/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Company Finance By ID
GET {{baseUrl}}/company-finances/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Company Finance
POST {{baseUrl}}/company-finances
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "saldo_company": 250000000.00
}

### Update Company Finance
PUT {{baseUrl}}/company-finances/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "saldo_company": 300000000.00
}

### Delete Company Finance
DELETE {{baseUrl}}/company-finances/1
Accept: application/json
Authorization: Bearer {{token}}

####################################
# SDM RESOURCE
####################################

### Get All SDM Resource
GET {{baseUrl}}/sdm-resources?search=GitHub&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get SDM Resources Paginated
GET {{baseUrl}}/sdm-resources/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get SDM Resource By ID
GET {{baseUrl}}/sdm-resources/1
Accept: application/json
Authorization: Bearer {{token}}

### Create SDM Resource
POST {{baseUrl}}/sdm-resources
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sdm_component": "Utilisasi Tim",
  "metrik": "Jam Kerja Proyek vs Internal",
  "capacity_target": "80% Proyek",
  "budget": 6000000.00,
  "actual": 5000000.00,
  "rag_status": "green",
  "notes": "Tim berhasil mencapai target utilisasi dengan baik."
}

### Update SDM Resources
PUT {{baseUrl}}/sdm-resources/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sdm_component": "Utilisasi Tim Updated",
  "metrik": "Jam Kerja Proyek vs Internal Updated",
  "capacity_target": "85% Proyek",
  "budget": 7000000.00,
  "actual": 6000000.00,
  "rag_status": "amber",
  "notes": "Tim mengalami sedikit penurunan dalam utilisasi."
}

### Delete SDM Resource
DELETE {{baseUrl}}/sdm-resources/1
Accept: application/json
Authorization: Bearer {{token}}

####################################
# INFRASTRUCTURE TOOL
####################################

### Get All Infrastructure Tools
GET {{baseUrl}}/infrastructure-tools?search=GitHub&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Infrastructure Tools Paginated
GET {{baseUrl}}/infrastructure-tools/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Infrastructure Tool By ID
GET {{baseUrl}}/infrastructure-tools/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Infrastructure Tool
POST {{baseUrl}}/infrastructure-tools
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tech_stack_component": "GitHub",
  "vendor": "GitHub Inc.",
  "monthly_fee": 29000000.99,
  "annual_fee": 299000000.99,
  "expired_date": "2026-09-18",
  "status": "active",
  "notes": "Version control and collaboration platform"
}

### Update Infrastructure Tool
PUT {{baseUrl}}/infrastructure-tools/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tech_stack_component": "GitHub Updated",
  "vendor": "GitHub Inc.",
  "monthly_fee": 30000000.00,
  "annual_fee": 310000000.00,
  "expired_date": "2027-09-18",
  "status": "inactive",
  "notes": "Updated version control platform"
}

### Delete Infrastructure Tool
DELETE {{baseUrl}}/infrastructure-tools/1
Accept: application/json
Authorization: Bearer {{token}}

####################################
# FIXED COST
####################################

### Get All Fixed Costs
GET {{baseUrl}}/fixed-costs?search=GitHub&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Fixed Costs Paginated
GET {{baseUrl}}/fixed-costs/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Fixed Cost By ID
GET {{baseUrl}}/fixed-costs/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Fixed Cost
POST {{baseUrl}}/fixed-costs
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "financial_items": "GitHub Subscription",
  "description": "Monthly subscription for GitHub services",
  "budget": 299000000.99,
  "actual": 29000000.99,
  "notes": "Used for version control and collaboration"
}

### Update Fixed Cost
PUT {{baseUrl}}/fixed-costs/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "financial_items": "GitHub Subscription Updated",
  "description": "Updated monthly subscription for GitHub services",
  "budget": 310000000.00,
  "actual": 30000000.00,
  "notes": "Updated usage for version control and collaboration"
}

### Delete Fixed Cost
DELETE {{baseUrl}}/fixed-costs/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# COMPANY ABOUT
####################################

### Get Company About
GET {{baseUrl}}/company-about
Accept: application/json
Authorization: Bearer {{token}}

### Get Company About By ID
GET {{baseUrl}}/company-about/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Company About
POST {{baseUrl}}/company-about
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "PT. Jendela Cakra Digital",
  "description": "Employee Handbook 2024",
  "vision": "Menjadi perusahaan teknologi terdepan di Indonesia yang menghadirkan solusi digital, integrasi kecerdasan buatan, dan layanan konsultasi IT yang mampu mempercepat transformasi bisnis secara berkelanjutan.",
   "mission": ["Menghadirkan sistem dan aplikasi yang aman, scalable, dan sesuai kebutuhan pengguna."],
  "established_date": "",
  "branches": [],
  "address": "",
  "email": "contact@jcdigital.co.id",
  "phone": ""
}

### Update Company About
PUT {{baseUrl}}/company-about/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "PT. Jendela Cakra Digital",
  "description": "Employee Handbook 2024",
  "vision": "Menjadi perusahaan teknologi terdepan di Indonesia yang menghadirkan solusi digital, integrasi kecerdasan buatan, dan layanan konsultasi IT yang mampu mempercepat transformasi bisnis secara berkelanjutan.",
   "mission": ["Menghadirkan sistem dan aplikasi yang aman, scalable, dan sesuai kebutuhan pengguna."],
  "established_date": "",
  "branches": [],
  "address": "",
  "email": "contact@jcdigital.co.id",
  "phone": ""
}

### Delete Company About
DELETE {{baseUrl}}/company-about/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# Vendors
####################################

### Get Vendors by Search
GET {{baseUrl}}/vendors?search=Jendela&limit=10
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Pagination
GET {{baseUrl}}/vendors/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Vendors By ID
GET {{baseUrl}}/vendors/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Vendors
POST {{baseUrl}}/vendors
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "PT. Jendela Cakra Digital",
  "pic_name": "Rizky Ajie",
  "pic_phone": "+628123456789",
  "email": "contact@jcdigital.co.id",
  "address": "Jl. Merdeka No. 123, Jakarta, Indonesia",
  "type": "Technology",
  "field": "Software Development",
  "notes": "Vendor untuk pengembangan aplikasi internal dan konsultasi IT"
}


### Update Vendors
PUT {{baseUrl}}/vendors/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "PT. Jendela Cakra Digital",
  "pic_name": "Rizky Ajie Kurniawan",
  "pic_phone": "+628123456789",
  "email": "contact@jcdigital.co.id",
  "address": "Jl. Merdeka No. 123, Jakarta, Indonesia",
  "type": "Technology",
  "field": "Software Development",
  "notes": "Vendor untuk pengembangan aplikasi internal dan konsultasi IT"
}


### Delete Vendors
DELETE {{baseUrl}}/vendors/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# Vendors Task Pivot
####################################

### Get Vendors Task Pivot by Search
GET {{baseUrl}}/vendors-task-pivot?search=Jendela&limit=10
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Task Pivot by Pagination
GET {{baseUrl}}/vendors-task-pivot/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Task Pivot by Id
GET {{baseUrl}}/vendors-task-pivot/1
Accept: application/json
Authorization: Bearer {{token}}


### Create Vendors Task Pivot
POST {{baseUrl}}/vendors-task-pivot
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "vendor_id": 1,
  "maintenance": false,
  "contract_value": 5000000,
  "contract_status": "Active",
  "contract_start": "2026-01-02",
  "contract_end" : "2026-02-02"
}


### Update Vendors Task Pivot
PUT {{baseUrl}}/vendors-task-pivot/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "vendor_id": 1,
  "vendor_task_id": 1,
  "role": "lead developer",
  "assigned_date": "2026-01-03",
  "notes": "Update role tim"
}


### Delete Vendors Task Pivot by Id
DELETE {{baseUrl}}/vendors-task-pivot/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# Vendors Task List
####################################

### Get Vendors Task List by Search
GET {{baseUrl}}/vendors-task-list?search=Jendela&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Vendors Task List Pagination
GET {{baseUrl}}/vendors-task-list/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}

### Get Vendors by Id
GET {{baseUrl}}/vendors-task-list/1
Accept: application/json
Authorization: Bearer {{token}}

### Create Vendors Task List
POST {{baseUrl}}/vendors-task-list
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Inspect Vendor Equipment",
  "pivot_id": 1
}

### Update Vendors Task List
PUT {{baseUrl}}/vendors-task-list/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Task Name",
  "pivot_id": 1
}

### Delete Vendors Task List
DELETE {{baseUrl}}/vendors-task-list/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# Vendors Task Scope
####################################

### Get Vendors Task Scope by Search
GET {{baseUrl}}/vendors-task-scope?search=Jendela&limit=10
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Task Scope by Pagination
GET {{baseUrl}}/vendors-task-scope/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Task Scope by id
GET {{baseUrl}}/vendors-task-scope/1
Accept: application/json
Authorization: Bearer {{token}}


### Create Vendors Task Scope
POST {{baseUrl}}/vendors-task-scope
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Inspect Scope Vendor Equipment",
  "pivot_id": 1
}


### Update Vendors Task Scope by Id
PUT {{baseUrl}}/vendors-task-scope/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Updated Scope Name",
  "pivot_id": 1
}


### Delete Vendors Task Scope by Id
DELETE {{baseUrl}}/vendors-task-scope/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# Vendors Task Payment
####################################

### Get Vendors Task Payment by Search
GET {{baseUrl}}/vendors-task-payment?search=Jendela&limit=10
Accept: application/json
Authorization: Bearer {{token}}

### Get Vendors Task Payment by Pagination
GET {{baseUrl}}/vendors-task-payment/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Task Payment by Id
GET {{baseUrl}}/vendors-task-payment/1
Accept: application/json
Authorization: Bearer {{token}}


### Create Vendors Task Payment
POST {{baseUrl}}/vendors-task-payment
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "document_name": "Payment Termin 1",
  "document_path":  "vendors-payment/vendors-payment-test.pdf",
  "amount" : 2000000.00,
  "payment_date": "2006-04-20",
  "pivot_id": 1
}


### Update Vendors Task Payment
PUT {{baseUrl}}/vendors-task-payment/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "document_name": "Payment Termin 1",
  "document_path":  "vendors-payment/vendors-payment-test.pdf",
  "amount" : 2000000.00,
  "payment_date": "2006-04-20",
  "pivot_id": 1
}

### Delete Vendors Task Payment by Id
DELETE {{baseUrl}}/vendors-task-payment/1
Accept: application/json
Authorization: Bearer {{token}}


####################################
# Vendors Attachment
####################################

### Get Vendors Attachment by Search
GET {{baseUrl}}/vendors-task-attachment?search=Jendela&limit=10
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Attachment by Pagination
GET {{baseUrl}}/vendors-task-attachment/all/paginated?row_per_page=10&search=
Accept: application/json
Authorization: Bearer {{token}}


### Get Vendors Attachment by Id
GET {{baseUrl}}/vendors-task-attachment/1
Accept: application/json
Authorization: Bearer {{token}}


### Create Vendors Attachment
POST {{baseUrl}}/vendors-task-attachment
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "vendor_task_id": 1,
  "file_name": "specification.pdf",
  "file_url": "vendors-attachment/vendors-test.pdf",
  "notes": "Dokumen spesifikasi API"
}


### Update Vendors Attachment
PUT {{baseUrl}}/vendors-task-attachment/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "vendor_task_id": 1,
  "file_name": "specification_updated.pdf",
  "file_url": "https://example.com/specification_updated.pdf",
  "notes": "Update dokumen spesifikasi API"
}

### Delete Vendors Attachment by Id
DELETE {{baseUrl}}/vendors-task-attachment/1
Accept: application/json
Authorization: Bearer {{token}}


